# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28983cdbead7441e95fa5b9bae5a82bdc8ad24f9dd75aff67a6f9fb2643197a7f5fa416b0a6be299b90bf6534e7484abfe8e7cbce388bdd5d552e090d8a58e53

test:
  secret_key_base: d0f0f43dcce99749de9f9f30143ba875a908b5362cca203e2f2d60c9011d1a577b241f3a775c6c4155162afe5e225cfd1671b313302ce8d8e7aab7c08b44012d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
